CREATE TABLE PROJECTS(
        PROJECT_ID  NUMBER  PRIMARY KEY,
        PROJECT_DESCRIPTION VARCHAR(100) CHECK ( LENGTH(PROJECT_DESCRIPTION) > 10),
        PROJECT_INVESTMENTS NUMBER(8, -3) CHECK(PROJECT_INVESTMENTS > 0)
);

CREATE TABLE PROJECTS_EMPLOYEES(
PROJECT_ID NUMBER NOT NULL ,
EMPLOYEE_ID NUMBER NOT NULL ,
PROJECT_REVENUE NUMBER,
HOURS_SPEND NUMBER DEFAULT 0,
CONSTRAINTS FK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID),
CONSTRAINTS FK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);