CREATE TABLE EMPLOYMENT_LOG (
EMPLOYMENT_LOG_ID NUMBER(5) PRIMARY KEY,
FIRST_NAME VARCHAR (20),
LAST_NAME VARCHAR (25),
EMPLOYEE_ACTION VARCHAR (100) CHECK(EMPLOYEE_ACTION = 'HIRED' OR EMPLOYEE_ACTION = 'FIRED'),
EMPLOYMENT_STATUS_UPDTD_TMSTMP TIMESTAMP
)