CREATE OR REPLACE PROCEDURE INSERT_INTO_LOG
  (ID NUMBER, F_NAME VARCHAR, L_NAME VARCHAR, E_ACTION VARCHAR, EMPLOYMENT_STATUS TIMESTAMP)
IS
BEGIN
  INSERT INTO EMPLOYMENT_LOG(
   EMPLOYMENT_LOG_ID, FIRST_NAME, LAST_NAME, EMPLOYEE_ACTION, EMPLOYMENT_STATUS_UPDTD_TMSTMP)
   VALUES(
   ID, F_NAME, L_NAME,E_ACTION, EMPLOYMENT_STATUS);
END;

CREATE OR REPLACE TRIGGER INSERTED_IN_EMPLOYEE
AFTER INSERT OR DELETE
ON EMPLOYEES
FOR EACH ROW
BEGIN
 IF INSERTING
   THEN
       EXECUTE INSERT_INTO_LOG(NEW.EMPLOYEE_ID, NEW.FIRST_NAME, NEW.LAST_NAME, 'HIRED', CURRENT_TIMESTAMP);
   ELSE
       EXECUTE INSERT_INTO_LOG(OLD.EMPLOYEE_ID, OLD.FIRST_NAME, OLD.LAST_NAME, 'FIRED', CURRENT_TIMESTAMP);
 END IF;
END;