CREATE TABLE PAY(
        CARD_NR NUMBER(16) PRIMARY KEY,
        SALARY NUMBER (8, 2),
        COMMISSION_PCT NUMBER(2,2),
        EMPLOYEE_ID NUMBER(6),
        CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);
